import mongoose from "mongoose";
import DutySummary from "../models/DutySummary.js";
import ExamSchedule from "../models/ExamSchedule.js";
import { scheduleProgress, generateDutySummary } from "../services/dutySummaryService.js";
import { autoPromoteDuePlans } from "../services/planLifecycle.js";

/**
 * GET /api/duty-summary/:scheduleId
 * The saved summary (generated automatically when the schedule became
 * Complete) plus live progress ("3 of 5 plans published").
 */
export const getDutySummary = async (req, res) => {
    try {
        const { scheduleId } = req.params;
        if (!mongoose.isValidObjectId(scheduleId)) return res.status(400).json({ error: "Invalid schedule." });
        await autoPromoteDuePlans();
        const schedule = await ExamSchedule.findById(scheduleId).lean();
        if (!schedule) return res.status(404).json({ error: "Exam schedule not found." });
        const [progress, summary] = await Promise.all([
            scheduleProgress(scheduleId),
            DutySummary.findOne({ examScheduleId: scheduleId }).lean(),
        ]);
        res.json({ schedule, progress, summary });
    } catch (error) {
        console.error("Error fetching duty summary:", error);
        res.status(500).json({ error: "Failed to fetch duty summary" });
    }
};

/**
 * POST /api/duty-summary/:scheduleId/regenerate
 * Admin-triggered regeneration (e.g. a preview before the schedule is complete).
 */
export const regenerateDutySummary = async (req, res) => {
    try {
        const { scheduleId } = req.params;
        if (!mongoose.isValidObjectId(scheduleId)) return res.status(400).json({ error: "Invalid schedule." });
        const summary = await generateDutySummary(scheduleId, "regenerated by admin");
        if (!summary) return res.status(404).json({ error: "Exam schedule not found." });
        res.json({ message: "Duty summary regenerated", summary, progress: await scheduleProgress(scheduleId) });
    } catch (error) {
        console.error("Error regenerating duty summary:", error);
        res.status(500).json({ error: "Failed to regenerate duty summary" });
    }
};
